name: Continous Integrations

on:
  pull_request:
    branches:
      - main

jobs:
  automation_test_job:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.1.1
      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.2
        with:
          node-version: '20.12.x'
      - name: npm install and test
        run: |
          npm ci
          npm run ci:test
